name: Build Docker Image and Save Results

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build Docker image
        run: |
          docker build -t lilbeb:latest .
          docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push lilbeb:latest

      - name: Save results
        run: echo "Hello, Docker!" > result.txt

      - name: Save results to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-results
          path: result.txt
